services:
  rstudio-devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rstudio-devcontaier # docker exec -it rstudio-devcontaier bash
    environment:
      PASSWORD: "toor"
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8787:8787" # http://localhost:8787/ user: rstudio password: toor
      - "8888:8888" # http://localhost:8888/
    volumes:
      - ..:/workspaces:cached
      - vscode-extensions:/home/node/.vscode-server/extensions      
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
      - seccomp:unconfined
    restart: unless-stopped
    #entrypoint: ["/usr/local/bin/docker-entrypoint.sh"]    
    networks:
      - app-network    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
volumes:
  vscode-extensions:
    external: true
    
networks:
  app-network:
    external: true

